# Service definition to expose PostgreSQL database
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    service: postgres
  ports:
    - port: 5432
      targetPort: 5432
