# Pod definition for PostgreSQL database
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    service: postgres
spec:
  containers:
    - name: db
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports: 
        - containerPort: 5432
          name: postgres
