apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: postgres
    tier: db
spec:
  containers:
  - name: db
    image: postgres:latest
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    ports: 
    - containerPort: 5432