apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    app: result
    tier: frontend
spec:
  containers:
  - name: result
    image: dockersamples/examplevotingapp_result:v1
    ports:
    - containerPort: 80