apiVersion: v1
kind: Pod
metadata:
  name: results-app
  labels:
    app: resutls
    tier: frontend
  namespace: voting-app
spec:
  containers:
  - name: results
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - containerPort: 80