apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: voting
    tier: frontend
  namespace: voting-app
spec:
  containers:
    - name: voting
      image: kodekloud/examplevotingapp_vote:v1
      port: 80