apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    app: worker
    tier: backend
  namespace: voting-app
spec:
  containers:
    - name: worker
      image: kodekloud/examplevotingapp_worker:v1
