apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: my-backend
          image: nginx:latest
          ports:
            - containerPort: 80

