apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    name: frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: my-frontend
          image: nginx:latest
          ports:
            - containerPort: 80

