apiVersion: v1
kind: Service
metadata:
  name: np-service
spec:
  type: NodePort
  ports:
  - targetPort: 80   # application port
    port: 80         # service port
    nodePort: 30004  # node port
  selector:
    app: demo-app