apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: db
  template:
    metadata:
      name: db
      labels:
        app: postgres
        tier: db
    spec:
      containers:
      - name: db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports: 
        - containerPort: 5432