apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: db
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379