apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
      tier: frontend
  template:
    metadata:
      name: result
      labels:
        app: result
        tier: frontend
    spec:
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80