apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      tier: frontend
  template:
    metadata:
      labels:
        app: vote
        tier: frontend
    spec:
      containers:
      - name: vote
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
