apiVersion: apps/v1
kind: Service
metadata:
  name: results
  labels:
    app: results
spec:
  type: NodePort
  selector:
    app: result
    tier: frontend
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31000
