apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api-dep
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: my-api
          image: nginx:latest
          ports:
            - containerPort: 80